Start time: 06:55
dataset: spacev10m
N: 10000000
dataset file: /mnt/data/mocheng/dataset/spacev10m/base10M.fvecs
query file: /mnt/data/mocheng/dataset/spacev10m/query10k.fvecs
attr file: /mnt/data/mocheng/dataset/spacev10m/label/sel_1_500_random/attr_sel_1_500_random.json
query range file: /mnt/data/mocheng/dataset/spacev10m/label/sel_1_500_random/qrangesel_1_1_500_random_20.json
ground truth file: /mnt/data/mocheng/dataset/spacev10m/label/sel_1_500_random/sif_gt_sel_1_1_500_random_20_10.json
K: 10
nprobe: 400
collection name: collection_spacev10m_sel_1_500_random_100
2025-04-09 21:56:01,907 [ERROR][_create_connection]: Failed to create new connection using: 408dab3c9ab64259964d5d0085f978f5 (milvus_client.py:923)
Traceback (most recent call last):
  File "utils/pymilvus_ivfpq.py", line 67, in <module>
    client = MilvusClient(
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/milvus_client/milvus_client.py", line 67, in __init__
    self._using = self._create_connection(
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/milvus_client/milvus_client.py", line 924, in _create_connection
    raise ex from ex
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/milvus_client/milvus_client.py", line 921, in _create_connection
    connections.connect(using, user, password, db_name, token, uri=uri, **kwargs)
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/orm/connections.py", line 461, in connect
    connect_milvus(**kwargs, user=user, password=password, token=token, db_name=db_name)
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/orm/connections.py", line 411, in connect_milvus
    gh._wait_for_channel_ready(timeout=timeout)
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 155, in _wait_for_channel_ready
    raise MilvusException(
pymilvus.exceptions.MilvusException: <MilvusException: (code=2, message=Fail connecting to server on localhost:19530, illegal connection params or server unavailable)>
Command exited with non-zero status 1
	Command being timed: "python -u utils/pymilvus_ivfpq.py spacev10m 10000000 /mnt/data/mocheng/dataset/spacev10m/base10M.fvecs /mnt/data/mocheng/dataset/spacev10m/query10k.fvecs /mnt/data/mocheng/dataset/spacev10m/label/sel_1_500_random/attr_sel_1_500_random.json /mnt/data/mocheng/dataset/spacev10m/label/sel_1_500_random/qrangesel_1_1_500_random_20.json /mnt/data/mocheng/dataset/spacev10m/label/sel_1_500_random/sif_gt_sel_1_1_500_random_20_10.json 10 400 collection_spacev10m_sel_1_500_random_100 query 100 100"
	User time (seconds): 2.04
	System time (seconds): 0.09
	Percent of CPU this job got: 19%
	Elapsed (wall clock) time (h:mm:ss or m:ss): 0:10.65
	Average shared text size (kbytes): 0
	Average unshared data size (kbytes): 0
	Average stack size (kbytes): 0
	Average total size (kbytes): 0
	Maximum resident set size (kbytes): 77824
	Average resident set size (kbytes): 0
	Major (requiring I/O) page faults: 27
	Minor (reclaiming a frame) page faults: 22175
	Voluntary context switches: 2023
	Involuntary context switches: 513
	Swaps: 0
	File system inputs: 2888
	File system outputs: 0
	Socket messages sent: 0
	Socket messages received: 0
	Signals delivered: 0
	Page size (bytes): 4096
	Exit status: 1
Start time: 06:56
dataset: spacev10m
N: 10000000
dataset file: /mnt/data/mocheng/dataset/spacev10m/base10M.fvecs
query file: /mnt/data/mocheng/dataset/spacev10m/query10k.fvecs
attr file: /mnt/data/mocheng/dataset/spacev10m/label/sel_1_500_random/attr_sel_1_500_random.json
query range file: /mnt/data/mocheng/dataset/spacev10m/label/sel_1_500_random/qrangesel_1_1_500_random_20.json
ground truth file: /mnt/data/mocheng/dataset/spacev10m/label/sel_1_500_random/sif_gt_sel_1_1_500_random_20_10.json
K: 10
nprobe: 400
collection name: collection_spacev10m_sel_1_500_random_100
collection  collection_spacev10m_sel_1_500_random_100  exists
collection size: data: ["{'count(*)': 10000000}"]
query d: 100
get query szie: 10000
get range cnt: 10000
ngt= 10000  nq= 10000  k= 10
ids shape: 10000 10
gt shape: (10000, 10)
milvus get  94606  postive res from  100000  results, recall@ 10 : 0.94606
recall dist(10\% per bucket):  [0.000e+00 0.000e+00 0.000e+00 3.000e-04 5.000e-04 1.900e-03 5.800e-03
 2.110e-02 7.030e-02 2.977e-01 6.024e-01]
10000  queries cost: 139.1450526714325 , qps: 71.86744916912934
	Command being timed: "python -u utils/pymilvus_ivfpq.py spacev10m 10000000 /mnt/data/mocheng/dataset/spacev10m/base10M.fvecs /mnt/data/mocheng/dataset/spacev10m/query10k.fvecs /mnt/data/mocheng/dataset/spacev10m/label/sel_1_500_random/attr_sel_1_500_random.json /mnt/data/mocheng/dataset/spacev10m/label/sel_1_500_random/qrangesel_1_1_500_random_20.json /mnt/data/mocheng/dataset/spacev10m/label/sel_1_500_random/sif_gt_sel_1_1_500_random_20_10.json 10 400 collection_spacev10m_sel_1_500_random_100 query 100 100"
	User time (seconds): 23.48
	System time (seconds): 2.95
	Percent of CPU this job got: 15%
	Elapsed (wall clock) time (h:mm:ss or m:ss): 2:46.61
	Average shared text size (kbytes): 0
	Average unshared data size (kbytes): 0
	Average stack size (kbytes): 0
	Average total size (kbytes): 0
	Maximum resident set size (kbytes): 87768
	Average resident set size (kbytes): 0
	Major (requiring I/O) page faults: 22
	Minor (reclaiming a frame) page faults: 59431
	Voluntary context switches: 25683
	Involuntary context switches: 514221
	Swaps: 0
	File system inputs: 1576
	File system outputs: 24
	Socket messages sent: 0
	Socket messages received: 0
	Signals delivered: 0
	Page size (bytes): 4096
	Exit status: 0
