Start time: 08:11
dataset: sift1M
N: 1000000
dataset file: /mnt/data/mocheng/dataset/sift/sift_base.fvecs
query file: /mnt/data/mocheng/dataset/sift/sift_query.fvecs
attr file: /mnt/data/mocheng/dataset/sift/label/sel_1_100_random/attr_sel_1_100_random.json
query range file: /mnt/data/mocheng/dataset/sift/label/sel_1_100_random/qrangesel_1_1_100_random.json
ground truth file: /mnt/data/mocheng/dataset/sift/label/sel_1_100_random/sif_gt_sel_1_1_100_random_10.json
K: 10
M: 40
ef_construction: 1000
ef_search: 400
distribution: sel_1_100_random
collection name: collection_hnsw_sift1M_sel_1_100_random_efc1000
mode: construction
d: 128
Failed to create new connection using: d019748d1d2847beb387ea2193018fb0
Traceback (most recent call last):
  File "utils/pymilvus_hnsw.py", line 75, in <module>
    client = MilvusClient(
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/milvus_client/milvus_client.py", line 60, in __init__
    self._using = self._create_connection(
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/milvus_client/milvus_client.py", line 728, in _create_connection
    raise ex from ex
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/milvus_client/milvus_client.py", line 725, in _create_connection
    connections.connect(using, user, password, db_name, token, uri=uri, **kwargs)
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/orm/connections.py", line 449, in connect
    connect_milvus(**kwargs, user=user, password=password, token=token, db_name=db_name)
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/orm/connections.py", line 400, in connect_milvus
    gh._wait_for_channel_ready(timeout=timeout)
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 150, in _wait_for_channel_ready
    raise MilvusException(
pymilvus.exceptions.MilvusException: <MilvusException: (code=2, message=Fail connecting to server on localhost:19530, illegal connection params or server unavailable)>
Command exited with non-zero status 1
	Command being timed: "python -u utils/pymilvus_hnsw.py sift1M 1000000 /mnt/data/mocheng/dataset/sift/sift_base.fvecs /mnt/data/mocheng/dataset/sift/sift_query.fvecs /mnt/data/mocheng/dataset/sift/label/sel_1_100_random/attr_sel_1_100_random.json /mnt/data/mocheng/dataset/sift/label/sel_1_100_random/qrangesel_1_1_100_random.json /mnt/data/mocheng/dataset/sift/label/sel_1_100_random/sif_gt_sel_1_1_100_random_10.json 10 40 1000 400 sel_1_100_random collection_hnsw_sift1M_sel_1_100_random_efc1000 construction 128"
	User time (seconds): 13.32
	System time (seconds): 0.16
	Percent of CPU this job got: 129%
	Elapsed (wall clock) time (h:mm:ss or m:ss): 0:10.41
	Average shared text size (kbytes): 0
	Average unshared data size (kbytes): 0
	Average stack size (kbytes): 0
	Average total size (kbytes): 0
	Maximum resident set size (kbytes): 83968
	Average resident set size (kbytes): 0
	Major (requiring I/O) page faults: 0
	Minor (reclaiming a frame) page faults: 18402
	Voluntary context switches: 1911
	Involuntary context switches: 159
	Swaps: 0
	File system inputs: 0
	File system outputs: 8
	Socket messages sent: 0
	Socket messages received: 0
	Signals delivered: 0
	Page size (bytes): 4096
	Exit status: 1
Start time: 09:43
dataset: sift1M
N: 1000000
dataset file: /mnt/data/mocheng/dataset/sift/sift_base.fvecs
query file: /mnt/data/mocheng/dataset/sift/sift_query.fvecs
attr file: /mnt/data/mocheng/dataset/sift/label/sel_1_100_random/attr_sel_1_100_random.json
query range file: /mnt/data/mocheng/dataset/sift/label/sel_1_100_random/qrangesel_1_1_100_random.json
ground truth file: /mnt/data/mocheng/dataset/sift/label/sel_1_100_random/sif_gt_sel_1_1_100_random_10.json
K: 10
M: 40
ef_construction: 1000
ef_search: 400
distribution: sel_1_100_random
collection name: collection_hnsw_sift1M_sel_1_100_random_efc1000
mode: construction
d: 128
Failed to create new connection using: 5156cea37cc047adbe2247aa220da9cb
Traceback (most recent call last):
  File "utils/pymilvus_hnsw.py", line 75, in <module>
    client = MilvusClient(
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/milvus_client/milvus_client.py", line 60, in __init__
    self._using = self._create_connection(
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/milvus_client/milvus_client.py", line 728, in _create_connection
    raise ex from ex
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/milvus_client/milvus_client.py", line 725, in _create_connection
    connections.connect(using, user, password, db_name, token, uri=uri, **kwargs)
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/orm/connections.py", line 449, in connect
    connect_milvus(**kwargs, user=user, password=password, token=token, db_name=db_name)
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/orm/connections.py", line 400, in connect_milvus
    gh._wait_for_channel_ready(timeout=timeout)
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 150, in _wait_for_channel_ready
    raise MilvusException(
pymilvus.exceptions.MilvusException: <MilvusException: (code=2, message=Fail connecting to server on localhost:19530, illegal connection params or server unavailable)>
Command exited with non-zero status 1
	Command being timed: "python -u utils/pymilvus_hnsw.py sift1M 1000000 /mnt/data/mocheng/dataset/sift/sift_base.fvecs /mnt/data/mocheng/dataset/sift/sift_query.fvecs /mnt/data/mocheng/dataset/sift/label/sel_1_100_random/attr_sel_1_100_random.json /mnt/data/mocheng/dataset/sift/label/sel_1_100_random/qrangesel_1_1_100_random.json /mnt/data/mocheng/dataset/sift/label/sel_1_100_random/sif_gt_sel_1_1_100_random_10.json 10 40 1000 400 sel_1_100_random collection_hnsw_sift1M_sel_1_100_random_efc1000 construction 128"
	User time (seconds): 13.34
	System time (seconds): 0.16
	Percent of CPU this job got: 129%
	Elapsed (wall clock) time (h:mm:ss or m:ss): 0:10.42
	Average shared text size (kbytes): 0
	Average unshared data size (kbytes): 0
	Average stack size (kbytes): 0
	Average total size (kbytes): 0
	Maximum resident set size (kbytes): 83968
	Average resident set size (kbytes): 0
	Major (requiring I/O) page faults: 0
	Minor (reclaiming a frame) page faults: 18396
	Voluntary context switches: 1913
	Involuntary context switches: 148
	Swaps: 0
	File system inputs: 0
	File system outputs: 16
	Socket messages sent: 0
	Socket messages received: 0
	Signals delivered: 0
	Page size (bytes): 4096
	Exit status: 1
Start time: 11:14
dataset: sift1M
N: 1000000
dataset file: /mnt/data/mocheng/dataset/sift/sift_base.fvecs
query file: /mnt/data/mocheng/dataset/sift/sift_query.fvecs
attr file: /mnt/data/mocheng/dataset/sift/label/sel_1_100_random/attr_sel_1_100_random.json
query range file: /mnt/data/mocheng/dataset/sift/label/sel_1_100_random/qrangesel_1_1_100_random.json
ground truth file: /mnt/data/mocheng/dataset/sift/label/sel_1_100_random/sif_gt_sel_1_1_100_random_10.json
K: 10
M: 40
ef_construction: 1000
ef_search: 400
distribution: sel_1_100_random
collection name: collection_hnsw_sift1M_sel_1_100_random_efc1000
mode: construction
d: 128
Failed to create new connection using: e7097640931345e89627cd4e9873ce1f
Traceback (most recent call last):
  File "utils/pymilvus_hnsw.py", line 75, in <module>
    client = MilvusClient(
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/milvus_client/milvus_client.py", line 60, in __init__
    self._using = self._create_connection(
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/milvus_client/milvus_client.py", line 728, in _create_connection
    raise ex from ex
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/milvus_client/milvus_client.py", line 725, in _create_connection
    connections.connect(using, user, password, db_name, token, uri=uri, **kwargs)
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/orm/connections.py", line 449, in connect
    connect_milvus(**kwargs, user=user, password=password, token=token, db_name=db_name)
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/orm/connections.py", line 400, in connect_milvus
    gh._wait_for_channel_ready(timeout=timeout)
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 150, in _wait_for_channel_ready
    raise MilvusException(
pymilvus.exceptions.MilvusException: <MilvusException: (code=2, message=Fail connecting to server on localhost:19530, illegal connection params or server unavailable)>
Command exited with non-zero status 1
	Command being timed: "python -u utils/pymilvus_hnsw.py sift1M 1000000 /mnt/data/mocheng/dataset/sift/sift_base.fvecs /mnt/data/mocheng/dataset/sift/sift_query.fvecs /mnt/data/mocheng/dataset/sift/label/sel_1_100_random/attr_sel_1_100_random.json /mnt/data/mocheng/dataset/sift/label/sel_1_100_random/qrangesel_1_1_100_random.json /mnt/data/mocheng/dataset/sift/label/sel_1_100_random/sif_gt_sel_1_1_100_random_10.json 10 40 1000 400 sel_1_100_random collection_hnsw_sift1M_sel_1_100_random_efc1000 construction 128"
	User time (seconds): 13.31
	System time (seconds): 0.14
	Percent of CPU this job got: 129%
	Elapsed (wall clock) time (h:mm:ss or m:ss): 0:10.38
	Average shared text size (kbytes): 0
	Average unshared data size (kbytes): 0
	Average stack size (kbytes): 0
	Average total size (kbytes): 0
	Maximum resident set size (kbytes): 83968
	Average resident set size (kbytes): 0
	Major (requiring I/O) page faults: 0
	Minor (reclaiming a frame) page faults: 18417
	Voluntary context switches: 1847
	Involuntary context switches: 121
	Swaps: 0
	File system inputs: 0
	File system outputs: 16
	Socket messages sent: 0
	Socket messages received: 0
	Signals delivered: 0
	Page size (bytes): 4096
	Exit status: 1
Start time: 12:45
dataset: sift1M
N: 1000000
dataset file: /mnt/data/mocheng/dataset/sift/sift_base.fvecs
query file: /mnt/data/mocheng/dataset/sift/sift_query.fvecs
attr file: /mnt/data/mocheng/dataset/sift/label/sel_1_100_random/attr_sel_1_100_random.json
query range file: /mnt/data/mocheng/dataset/sift/label/sel_1_100_random/qrangesel_1_1_100_random.json
ground truth file: /mnt/data/mocheng/dataset/sift/label/sel_1_100_random/sif_gt_sel_1_1_100_random_10.json
K: 10
M: 40
ef_construction: 1000
ef_search: 400
distribution: sel_1_100_random
collection name: collection_hnsw_sift1M_sel_1_100_random_efc1000
mode: construction
d: 128
Failed to create new connection using: 8538995052e54306b9d5e56b5f10cca5
Traceback (most recent call last):
  File "utils/pymilvus_hnsw.py", line 75, in <module>
    client = MilvusClient(
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/milvus_client/milvus_client.py", line 60, in __init__
    self._using = self._create_connection(
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/milvus_client/milvus_client.py", line 728, in _create_connection
    raise ex from ex
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/milvus_client/milvus_client.py", line 725, in _create_connection
    connections.connect(using, user, password, db_name, token, uri=uri, **kwargs)
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/orm/connections.py", line 449, in connect
    connect_milvus(**kwargs, user=user, password=password, token=token, db_name=db_name)
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/orm/connections.py", line 400, in connect_milvus
    gh._wait_for_channel_ready(timeout=timeout)
  File "/home/mocheng/anaconda3/envs/py38/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 150, in _wait_for_channel_ready
    raise MilvusException(
pymilvus.exceptions.MilvusException: <MilvusException: (code=2, message=Fail connecting to server on localhost:19530, illegal connection params or server unavailable)>
Command exited with non-zero status 1
	Command being timed: "python -u utils/pymilvus_hnsw.py sift1M 1000000 /mnt/data/mocheng/dataset/sift/sift_base.fvecs /mnt/data/mocheng/dataset/sift/sift_query.fvecs /mnt/data/mocheng/dataset/sift/label/sel_1_100_random/attr_sel_1_100_random.json /mnt/data/mocheng/dataset/sift/label/sel_1_100_random/qrangesel_1_1_100_random.json /mnt/data/mocheng/dataset/sift/label/sel_1_100_random/sif_gt_sel_1_1_100_random_10.json 10 40 1000 400 sel_1_100_random collection_hnsw_sift1M_sel_1_100_random_efc1000 construction 128"
	User time (seconds): 13.28
	System time (seconds): 0.16
	Percent of CPU this job got: 129%
	Elapsed (wall clock) time (h:mm:ss or m:ss): 0:10.39
	Average shared text size (kbytes): 0
	Average unshared data size (kbytes): 0
	Average stack size (kbytes): 0
	Average total size (kbytes): 0
	Maximum resident set size (kbytes): 83968
	Average resident set size (kbytes): 0
	Major (requiring I/O) page faults: 0
	Minor (reclaiming a frame) page faults: 18402
	Voluntary context switches: 1920
	Involuntary context switches: 183
	Swaps: 0
	File system inputs: 0
	File system outputs: 8
	Socket messages sent: 0
	Socket messages received: 0
	Signals delivered: 0
	Page size (bytes): 4096
	Exit status: 1
